module.exports = {
    BOARD: '#board',
    MESSAGE: '#message',
    FIRST_MOVE_CURRENT: '[name=space62]',
    FIRST_MOVE_TARGET: '[name=space73]',
    SECOND_MOVE_CURRENT: '[name=space42]',
    SECOND_MOVE_TARGET: '[name=space53]',
    THIRD_MOVE_CURRENT: '[name=space51]',
    THIRD_MOVE_TARGET: '[name=space62]',
    FOURTH_MOVE_CURRENT: '[name=space40]',
    FOURTH_MOVE_TARGET: '[name=space51]',
    FIFTH_MOVE_CURRENT: '[name=space53]',
    FIFTH_MOVE_TARGET: '[name=space35]',
    BLUE_CHECKER: '[src="me1.gif"]',
    RESTART_BUTTON: 'a:text("Restart...")',
    CHECKER_YOU1: 'you1.gif',
    CHECKER_YOU2: 'you2.gif',
    CHECKER_GRAY: 'gray.gif',
};
